version: '3.7'

services:
  instagram-to-discord:
    image: ghcr.io/jim60105/docker-instagram-to-discord
    # build: .
    labels:
      - 'instagram-to-discord'
    restart: on-failure:3
    volumes:
      - ./config.yml:/usr/src/app/config.yml:ro
      - db:/usr/src/app/db
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:12201"

  # Start container every day. (if it's not running)
  jobber:
    image: blacklabelops/jobber:docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - JOB_NAME1=start
      - JOB_COMMAND1=docker start $$(docker ps -aqf "label=instagram-to-discord")
      - JOB_TIME1=0 0 0 * * * #Every day
      - JOB_NOTIFY_ERR1=false
      - JOB_NOTIFY_FAIL1=false

volumes:
  db:
