version: '3.7'

services:
  instagram-to-discord:
    image: ghcr.io/jim60105/docker-instagram-to-discord
    # build: .
    restart: always
    volumes:
      - ./config.yml:/usr/src/app/config.yml:ro
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:12201"
